# MAIN

baseURL = 'https://anlar.github.io/'

theme = 'roadster'

defaultContentLanguage = 'en'

[permalinks]
  posts = '/:year-:month-:day-:filename/'

[markup]
  [markup.highlight]
    style = "github"
    lineNos = true
    anchorLineNos = true

# MENU

[languages]
 [languages.en]
    languageCode = 'en'
    languageName = 'English'
    title = 'Blog AnLar'
    weight = 1
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Blog'
        pageRef = '/'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Tags'
        pageRef = '/tags'
        weight = 20
      [[languages.en.menus.main]]
        name = 'About'
        url = '/about'
        weight = 30
  [languages.ru]
    languageCode = 'ru'
    languageName = 'Русский'
    title = 'Блог AnLar'
    weight = 2
    [languages.ru.menus]
      [[languages.ru.menus.main]]
        name = 'Блог'
        pageRef = '/'
        weight = 10
      [[languages.ru.menus.main]]
        name = 'Теги'
        pageRef = '/tags'
        weight = 20
      [[languages.ru.menus.main]]
        name = 'Обо мне'
        url = '/ru/about'
        weight = 30

# THEME: ROADSTER


[Params.logo]
  image = false

[Params.style.vars]
  highlightColor = "#046307"

[Params]
  post_meta = ["date"]

[Params.sidebar]
  home = "right"
  list = "right"
  single = false
  widgets = ["recent", "taglist", "social", "languages"]

[Params.widgets]
  tags_counter = true

[Params.widgets.social]
  github = "anlar"
  linkedin = "anton-larionov"
